name: Frontend CICD pipeline
on:
  #workflow_run:
  #  workflows: ["Test CICD for Backend Deployment"]
  #  types:
  #    - completed

  push:
    branches:
      - main


permissions:
    contents: read
    id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #checking out repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      #setting up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
         python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./frontend/requirements.txt


      #adding aws configuration credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "arn:aws:iam::767397972310:role/Java_Build"
          aws-region: us-east-1

      # valifying login to AWS
      - name: Validate AWS Login
        run: aws sts get-caller-identity

      # if varification is successful, then print the message else print the error message
      - name: Print Success Message
        run: echo "AWS Login Successful"
      - name: Print Error Message
        if: failure()
        run: echo "AWS Login Failed"

      # Compile all Python files to check for syntax errors
      - name: Build Python Code
        run: |
          python -m compileall .

      # Create deployment package
      - name: Package Frontend
        run: |
          cd frontend
          zip -r ../frontend.zip .

      # Upload artifact to S3
      - name: Upload to S3
        run: |
          aws s3 cp frontend.zip s3://javaprojectartifacts30june/artifacts/frontend.zip