name: "Test CICD for Frontend Deployment"
on:
  push:
    branches:
      - main

permissions:
    contents: read
    id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # checking out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # seting up java packages
      - name: Set up java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # cleaning the build directory
      - name: clean build directory
        working-directory: ./backend
        run: mvn clean
     
     #adding aws configuration credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "arn:aws:iam::767397972310:role/Java_Build"
          aws-region: us-east-1

      # valifying login to AWS
      - name: Validate AWS Login
        run: aws sts get-caller-identity

      # if varification is successful, then print the message else print the error message
      - name: Print Success Message
        run: echo "AWS Login Successful"
      - name: Print Error Message
        if: failure()
        run: echo "AWS Login Failed"

      # building the backend project
      - name: Build Backend Project
        working-directory: ./backend
        run: mvn package

      # listing all files in target folder
      - name: List target directory
        working-directory: ./backend
        run: ls -lh target/

    # check if the build was successful or not
      - name: Check Build Status
        if: success()
        run: echo "Build Successful"
      - name: Check Build Status
        if: failure()
        run: echo "Build Failed"

    # move the build output to S3 bucket using OIDC
      - name: Upload JAR to S3
        run:  aws s3 cp target/app.jar s3://javaprojectartifacts30june/backend/app.jar

      - name: Verify Upload
        run: aws s3 ls s3://javaprojectartifacts30june/backend/